dist: trusty
sudo: required
language: cpp

matrix:
  include:
    - os: osx
      compiler: clang
      env: Build, Test & Deploy
      osx_image: xcode10
      addons:
        homebrew:
          packages:
          - libzip
          - portaudio
          - libsndfile
          - libsamplerate
          update: true
      script:
        - |
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
